# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Mobius Resume"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://github.com/vickylaixy/hugo-theme-introduction/blob/master/LICENSE.md"
description = "Minimal, single page, smooth scrolling theme for Hugo."
homepage = "https://github.com/vickylaixy/hugo-theme-introduction"
tags = ["clean", "minimal"]
features = ["responsive", "single page"]
min_version = 001.

[author]
  name = "Mel Eaton"
  homepage = "https://mel-eaton.com"

# If porting an existing theme
[original]
  name = "vicky lai"
  homepage = "https://github.com/vickylaixy/hugo-theme-introduction"
  repo = "https://github.com/vickylaixy/hugo-theme-introduction/blob/master"
